__author__ = "Hammad Aslam Khan"
__description__ = "ML Pipeline"
__copyright__ = "Copyright ENGIE 2019"
__credits__ = ["Hammad"]
__license__ = "MIT"
__version__ = "1.0.1"
__maintainer__ = "Hammad"
__email__ = "raohammad@gmail.com"
__status__ = "NA"

# AutoGenerated by VX ML Pipeline #
from source.sourcetemplate import SourceTemplate
from target.targettemplate import TargetTemplate
from source.kafkasource import KafkaSource
from source.dummysource import DummySource
from target.kafkatarget import KafkaTarget
from target.dummytarget import DummyTarget
from nn.nntemplate import NNTemplate
from nn.nnResNet50v1 import NNResNet50v1
from nn.nnResNet50v2 import NNResNet50v2
from nn.nnResNet18v1 import NNResNet18v1
from nn.nnResNet18v2 import NNResNet18v2
from nn.nnResNet34v1 import NNResNet34v1
from nn.nnResNet34v2 import NNResNet34v2
from nn.nnResNet101v1 import NNResNet101v1
from nn.nnResNet101v2 import NNResNet101v2
from nn.nnResNet152v1 import NNResNet152v1
from nn.nnResNet152v2 import NNResNet152v2
from nn.nnSqueezeNet import NNSqueezeNet
from nn.nnVGG import NNVGG
from common.args import Args



source55Args = Args()
source55Args.label = 'dummy'
source55Args.name = 'dummysource'
source55Args.attribute = 'value'

target60Args = Args()
target60Args.ip = '127.0.0.1'
target60Args.port = '9902'
target60Args.topicout = 'output'

nn57Args = Args()
nn57Args.id = '57'
nn57Args.name = 'DummyNN'

NNTemplate57 = NNTemplate(nn57Args)

NNTemplate57.execute([DummySource(source55Args)],[KafkaTarget(target60Args)])

del NNTemplate57